### PR TITLE
Containerized CI and reusable workflow implementation

### PR DESCRIPTION
**Pull request by mlee03**
**Description**
In this PR, the CI workflow is changed to run in a [container](https://github.com/orgs/NOAA-GFDL/packages/container/package/miniforge). The image is built from a base miniforge image. GNU compilers, netCDF and HDF5 libraries, and MPICH have been installed. The default python version is set to 3.11.7.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] Targeted model if this changed was triggered by a model need/shortcoming

### CODE REVIEW

**Comment by mlee03** [comment]
Not ready.

**Review by FlorianDeconinck — DISMISSED** [review]
LGTM

**Review by fmalatino — DISMISSED** [review]
lgtm

**Review by xyuan — DISMISSED** [review]

**Review by oelbert — DISMISSED** [review]
👍

**Review by fmalatino — COMMENTED** [review]
I think the tests may be failing because `numpy` needs to be pinned to `1.26.4`

**Review by fmalatino — APPROVED** [review]
lgtm

**Pull request merged**
